"""packets table

Revision ID: 4cf0d5114ae0
Revises: 271da97d81f5
Create Date: 2022-02-17 19:52:03.617610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cf0d5114ae0'
down_revision = '271da97d81f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packet', sa.Column('test_taken', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_packet_test_taken'), 'packet', ['test_taken'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packet_test_taken'), table_name='packet')
    op.drop_column('packet', 'test_taken')
    # ### end Alembic commands ###
