"""packet table

Revision ID: 57820ddd21ce
Revises: edd529e6b409
Create Date: 2022-02-10 12:55:48.303305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57820ddd21ce'
down_revision = 'edd529e6b409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('packet_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_packet_count'), 'user', ['packet_count'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_packet_count'), table_name='user')
    op.drop_column('user', 'packet_count')
    # ### end Alembic commands ###
