"""users table

Revision ID: 78a1ce04a32e
Revises: 64155049fa16
Create Date: 2022-01-27 21:58:30.533996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a1ce04a32e'
down_revision = '64155049fa16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('DOB', sa.String(length=6), nullable=True))
    op.create_index(op.f('ix_user_DOB'), 'user', ['DOB'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_DOB'), table_name='user')
    op.drop_column('user', 'DOB')
    # ### end Alembic commands ###
