"""empty message

Revision ID: ddac0ac85693
Revises: 7dac9b8b53e2
Create Date: 2022-02-12 02:01:49.425574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddac0ac85693'
down_revision = '7dac9b8b53e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packet', 'packet_count_store')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packet', sa.Column('packet_count_store', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
